### ISSUE TITLE
zenodo 

### ISSUE THREAD

**Issue by garciagenrique** [SiLeBAT/zenodo-python#2]
Hi !

First of all, nice library :-) ! 

I'm currently trying to create an automatic deployment between GitLab and zenodo, and basically I coded a less classy library by my own (until I discovered this repo - which I'm going to fork and star immediately ;-) ).  However, I'm facing a couple of problems with zenodo and I was wondering that you might had also faced them and could give a clue.

My workflow is: check connection - create empty entry and recover some info - upload file(s) - update compulsory information - publish. 

The request answer that I receive seems correct; `status_code == 202` and when looking into the returned dictionary I have `... 'state': 'done', 'submitted': True, ...`. However, when I check in zenodo (sandbox) I cannot find the publication. On the contrary, it is saved as a draft and unless I do not go explicitly to the created deposit and click `Publish`, the entry rests as a draft. 

Also, if I list the deposition created, now I find that `... 'state': 'inprogress',  'submitted': True,  #...`.

Thanks in advance in any case !

**Comment by miguelalba** [comment]
Hi @garciagenrique,

thanks for checking this library. I have not used it in a while and wrote it from the snippets in the Zenodo documentation. It is probably outdated but I will look into it. Thanks for the pull request.

**Comment by garciagenrique** [comment]
Hi @miguelalba,
I have already contact the zenodo team, so I will be closing the issue. Thanks for your answer in any case !

The library hands the requests perfectly, so it is just the response of zenodo. For the record, in case this happens - the entry is published but the status is `inprogress` or you do not see the entry published in zenodo -, just click the publish button again in the deposition page of the entry, i.e., `...org/deposit/:deposition_id`.

Cheers !

**Comment by abubelinha** [comment]
@garciagenrique did you finally get this working? 
I don’t: https://github.com/SiLeBAT/zenodo-python/issues/6
